import Foundation

/// Pure, side-effect-free helpers extracted from the app-layer `UpdateManager`
/// so the update pipeline's riskiest logic — bundle verification, app-bundle
/// discovery, and swap-helper script generation — is unit-testable without
/// actually swapping the running app or launching a detached `Process`.
///
/// The irreducible side-effects (URLSession download, `Process.run`) stay in
/// `UpdateManager`; everything that *can* be pure lives here.
public enum UpdateInstaller {
    /// The bundle id the app expects of itself. A downloaded update whose
    /// `CFBundleIdentifier` differs is refused — it's not MacTidy.
    public static let expectedBundleID = "com.jayansh.mactidy"

    /// Locates a `*.app` bundle inside a staging directory, at the root or one
    /// level deep (a zip that wraps a top folder). Returns nil when there's no
    /// `.app` at either level — the caller treats that as `notAppBundle`.
    public static func findAppBundle(in dir: URL) -> URL? {
        let fm = FileManager.default
        guard let names = try? fm.contentsOfDirectory(atPath: dir.path) else { return nil }
        for name in names where name.hasSuffix(".app") {
            return dir.appendingPathComponent(name, isDirectory: true)
        }
        for name in names {
            let sub = dir.appendingPathComponent(name, isDirectory: true)
            var isDir: ObjCBool = false
            if fm.fileExists(atPath: sub.path, isDirectory: &isDir), isDir.boolValue,
               let inner = try? fm.contentsOfDirectory(atPath: sub.path) {
                for n in inner where n.hasSuffix(".app") {
                    return sub.appendingPathComponent(n, isDirectory: true)
                }
            }
        }
        return nil
    }

    /// What `verifyBundle` checks, surfaced so tests can assert which
    /// invariant rejected a bad bundle.
    public enum VerificationError: Error, Equatable {
        case notAppBundle
        case wrongBundle
        case signatureInvalid(String)
        case wrongVersion(found: String)
    }

    /// Verifies a candidate bundle before swapping anything. Checks, in order:
    /// 1. `Contents/MacOS/MacTidy` exists and is executable (real bundle).
    /// 2. `CFBundleIdentifier` == `expectedBundleID` (the right app).
    /// 3. `codesign -v` passes (download wasn't truncated/corrupted).
    /// 4. Its version is strictly newer than `currentVersion` (no downgrades).
    ///
    /// `codesignVerify` is injectable so tests don't shell out to `/usr/bin/codesign`;
    /// production passes `{ Shell.run("/usr/bin/codesign", ["-v", $0.path]) }`.
    public static func verifyBundle(
        at appURL: URL,
        expectedVersion: UpdateChecker.Version,
        currentVersion: UpdateChecker.Version,
        codesignVerify: (URL) -> Shell.Output?
    ) throws {
        let exe = appURL.appendingPathComponent("Contents/MacOS/MacTidy")
        guard FileManager.default.isExecutableFile(atPath: exe.path) else {
            throw VerificationError.notAppBundle
        }
        let plist = appURL.appendingPathComponent("Contents/Info.plist")
        guard let info = NSDictionary(contentsOfFile: plist.path),
              let bundleID = info["CFBundleIdentifier"] as? String,
              bundleID == expectedBundleID else {
            throw VerificationError.wrongBundle
        }
        if let r = codesignVerify(appURL), !r.succeeded {
            throw VerificationError.signatureInvalid(r.stderr)
        }
        let v = (info["CFBundleShortVersionString"] as? String) ?? "0"
        let found = UpdateChecker.Version(v)
        guard found == expectedVersion, found > currentVersion else {
            throw VerificationError.wrongVersion(found: v)
        }
    }

    /// Generates the detached swap-helper script that replaces the installed
    /// app after the current process quits. Pure — returns the script text so
    /// the caller writes it to a temp file and launches it. Tests pin the
    /// script's contract: it must `rm -rf` the old bundle (NOT Finder-delete),
    /// `mv` the new one in, strip quarantine, relaunch, and self-delete.
    public static func swapHelperScript(
        newAppURL: URL,
        installURL: URL,
        currentPID: Int32
    ) -> String {
        return """
        #!/bin/sh
        # Auto-generated by MacTidy to apply a self-update. Detached + disowned.
        log() { echo "$(date '+%H:%M:%S') $*"; }

        NEW_APP="\(newAppURL.path)"
        DEST="\(installURL.path)"
        LOG="$HOME/Library/Logs/MacTidy-update.log"
        exec >>"$LOG" 2>&1
        log "=== swap helper started (old pid \(currentPID)) ==="

        i=0
        while [ $i -lt 300 ]; do
            if ! kill -0 \(currentPID) 2>/dev/null; then break; fi
            sleep 0.2
            i=$((i + 1))
        done
        log "old process gone, swapping"

        if [ -e "$DEST" ]; then
            rm -rf "$DEST"
            log "old app removed"
        fi

        mv "$NEW_APP" "$DEST"
        log "new app moved"

        xattr -dr com.apple.quarantine "$DEST" 2>/dev/null || true

        open "$DEST"
        log "relaunched"

        rm -f "$0"
        """
    }
}